// Vendors the woff2 files this site actually uses out of the Fontsource
// packages, and regenerates the @font-face rules from the same source.
//
// Fonts are self-hosted rather than loaded from fonts.googleapis.com so that
// the files sit on the origin that already served the HTML, and so that the
// ones needed for first paint can be preloaded. Preloading is the point: the
// browser cannot discover a font URL inside Google's stylesheet until that
// stylesheet has arrived, which puts three sequential round trips in front of
// the first line of text.
//
// Run `pnpm sync-fonts` after changing the list below or bumping a package.
// Do not hand-edit public/fonts or src/styles/fonts.css.

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "public/fonts");
const cssPath = join(root, "src/styles/fonts.css");

// Only the latin subset, only the weight axis, and italics only where the site
// renders them. Two deliberate omissions, both measured:
//
//   opsz  Source Serif 4 with the optical-size axis is 122 KB against 51 KB
//         for weight alone. The serif runs 20-48px here; the axis is not worth
//         71 KB on a page whose entire HTML and CSS come to 28 KB.
//   latin-ext  Adds 117 KB across the three families. The latin subset already
//         covers U+0000-00FF and General Punctuation, so the middle dots, em
//         dashes and curly quotes in the copy are in range.
//
// The src format token is "woff2", not the "woff2-variations" that Fontsource
// emits. Every browser that supports variable fonts supports woff2, and
// "woff2-variations" is a non-standard token a browser is free not to match —
// in which case it skips the whole @font-face and falls back to Georgia.
const faces = [
  { pkg: "source-serif-4", family: "Source Serif 4", weight: "200 900", style: "normal" },
  { pkg: "source-serif-4", family: "Source Serif 4", weight: "200 900", style: "italic" },
  { pkg: "source-sans-3", family: "Source Sans 3", weight: "200 900", style: "normal" },
  { pkg: "source-sans-3", family: "Source Sans 3", weight: "200 900", style: "italic" },
  { pkg: "jetbrains-mono", family: "JetBrains Mono", weight: "100 800", style: "normal" },
];

mkdirSync(outDir, { recursive: true });

const blocks = [];
const manifest = [];

for (const face of faces) {
  const pkgDir = join(root, "node_modules/@fontsource-variable", face.pkg);
  const file = `${face.pkg}-latin-wght-${face.style}.woff2`;
  const version = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8")).version;
  const range = JSON.parse(readFileSync(join(pkgDir, "unicode.json"), "utf8")).latin;

  copyFileSync(join(pkgDir, "files", file), join(outDir, file));

  blocks.push(
    `@font-face {\n` +
      `  font-family: "${face.family}";\n` +
      `  font-style: ${face.style};\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url("/fonts/${file}") format("woff2");\n` +
      `  unicode-range: ${range};\n` +
      `}`,
  );
  manifest.push(`@fontsource-variable/${face.pkg}@${version} -> ${file}`);
}

writeFileSync(
  cssPath,
  `/* Generated by scripts/sync-fonts.mjs. Do not edit by hand.\n *\n` +
    manifest.map((line) => ` * ${line}`).join("\n") +
    `\n *\n * All three families are SIL Open Font License 1.1; see public/fonts/LICENSE.\n */\n\n` +
    blocks.join("\n\n") +
    "\n",
);

copyFileSync(
  join(root, "node_modules/@fontsource-variable/source-serif-4/LICENSE"),
  join(outDir, "LICENSE"),
);

console.log(`synced ${faces.length} faces to public/fonts and regenerated src/styles/fonts.css`);
