name: Merge Schedule

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # every day
    - cron: "0 0 * * *"

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2.4.0
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: merge
          # Require all pull request statuses to be successful before
          # merging. Default is `false`.
          require_statuses_success: "true"
          # Label to apply to the pull request if the merge fails. Default is
          # `automerge-fail`.
          automerge_fail_label: "merge-schedule-failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
